app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# Class for the table that manages users,
class User(db.Model,UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    age = db.Column(db.Integer)
    email = db.Column(db.String(255), unique=True, index=True)
    bio = db.Column(db.String(255))
    pass_key = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String(255))
    user_pitch = db.relationship('Pitches', backref='user', lazy='dynamic')

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_key = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_key, password)







class Pitches(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    pitch = db.Column(db.String(255))
    category = db.Column(db.String(255))
    posted = db.Column(db.DateTime, default=datetime.utcnow)
    the_comment = db.relationship('Comments', backref='pitch', lazy="dynamic")
    poster = db.Column(db.Integer, db.ForeignKey('users.id'))



    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitchs(cls, id):
        pitches = Pitches.query.filter_by(poster=id).all()
        return pitches


class Comments(db.Model):
    __tablename__="comments"
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    pitch_comment = db.Column(db.Integer, db.ForeignKey('pitches.id'))






    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, id):
        comments = Comments.query.filter_by(pitch_comment=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import Required,Email,EqualTo

from wtforms import StringField,PasswordField,BooleanField,SubmitField,TextAreaField,RadioField


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')


class NewPitch(FlaskForm):
    title = StringField('Title :',validators=[Required()])
    a_pitch = TextAreaField('New Pitch',validators=[Required()])
    category = StringField('Category :',validators=[Required()])
    submit = SubmitField('Submit', validators=[Required()])


class NewComment(FlaskForm):
    name = StringField('Name :',validators=[Required()])
    comment = TextAreaField('Comment.',validators = [Required()])
    submit = SubmitField('Submit', validators=[Required()])

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE



bootstrap=Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    #database app instance
    db.init_app(app)

    mail.init_app(app)
    simple.init_app(app)

    # Login manage instance
    login_manager.init_app(app)

    # configure UploadSet
    configure_uploads(app, photos)

    #bootstrap app instance
    bootstrap.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors,forms

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from ..models import User,Comments,Pitches
from .. import db,photos
from .forms import UpdateProfile ,NewPitch, NewComment
from flask_login import login_required,current_user
import markdown2

# Views for our templates
@main.route('/')
def index():
    '''
    View function to render the index html template
    '''
    pitchess = Pitches.query.all()

    return render_template('index.html',pitchess = pitchess)


@main.route('/category/<cat_input>')
def categories(cat_input):
    '''
    view function to display the pitches of our specific category
    '''
    category_list = Pitches.query.filter_by(category = cat_input).all()



    return render_template('categories.html',category = category_list)


@main.route('/pitch/<int:id>')
def pitch(id):
    '''
    View function to view a pitch
    '''
    the_pitch = Pitches.query.get(id)
    if the_pitch is None:
        abort(404)

    the_pitches = markdown2.markdown(the_pitch.pitch, extras=["code-friendly", "fenced-code-blocks"])
    commentss = Comments.get_comments(id)

    return render_template('pitch.html',pitch = pitch, the_pitch = the_pitch, comments = commentss)



@main.route('/pitch/add', methods = ['GET','POST'])
@login_required
def new_pitch():
    '''
    View function to create a new pitch
    '''
    form = NewPitch()
    if form.validate_on_submit():


        new_pitch = Pitches(title = form.title.data,pitch = form.a_pitch.data,category = form.category.data)

        new_pitch.save_pitch()
        return redirect(url_for('main.index'))

    title = "I Pitch"

    return render_template('new_pitch.html', title = title, pitch_form = form)




@main.route('/pitch/new_comment/<id>', methods = ['GET','POST'])
@login_required
def new_comments(id):
    '''
    View function to create a new comment to a pitch
    '''
    pitch = Pitches.query.filter_by(id=id).first()
    comment_form = NewComment()
    if comment_form.validate_on_submit():
        new_comment = Comments(comment=comment_form.comment.data, pitch_comment=id,)
        new_comment.save_comment()

        return redirect(url_for('main.index'))
    title = 'What do you think about that pitch? '

    return render_template('new_comment.html',title = title,form=comment_form, pitch = pitch)

@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/categories.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Pitch A Minute </title>
        {% endif %}
    </head>
    {% extends 'base.html'%}
    {% import 'macros.html' as macro%}


 <body>
    {% block content %}

    <h2>{{category_list}}</h2>

    {{macro.displayCategories( category_list ) }}



    {% endblock %}

 </body>

app/templates/foUfo.html
{% extends 'base.html'%}

{% block content %}
    <h1>We shall Pitch for you're search to be active, for know please go back to previous page!</h1>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> Pitch A Minute </title>
    {% endif %}
</head>
{% extends 'base.html'%}
{% import 'macros.html' as macro%}


<body>
{% block content %}

<h2> Pitches </h2>


<!--<div class="col-md-6">-->
    {% for pitch in pitchess %}
    <div class="container-fluid">
        <div class="card bg-light mb-3" style="max-width: 18rem;">
            <div class="card">
                <h1 class ='card-title'>{{pitch.title}}</h1>
                <div class="card-body">
                <p class="card-text">{{pitch.pitch}}</p>
                <p class="card-text">{{pitch.posted}}</p>
                <a class="btn btn-primary" href="/pitch/{{pitch.id}}">More Details</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}






    {% endblock %}

</body>

</html>

app/templates/macros.html
{% macro displayCategories(category_list) %}

{% for cat_pitch in category_list %}
 <div class="'container">
     <div class="row">
         <div class="col-md-6">
            <li>
                {{cat_pitch.category}}
            </li>
             <a href="/pitch{{cat_pitch.id}}" class="btn btn-primary"></a>
         </div>
     </div>
 </div>
{% endfor %}
{% endmacro %}


{% macro displayComments(comment_list) %}

{% for comment in comment_list %}

<div class="container">
    <div class="col-md-6">
        <h1>{{comment.comment}}</h1>
    </div>

</div>

{% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <h2>Pitch A Minute</h2>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-primary" href="/">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="btn btn-success" href="/pitch/add">New Pitch</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/category/Pick Up Lines">Pick Up Lines</a>
              <a class="dropdown-item" href="/category/Interview Pitch">Interview Pitch</a>
              <a class="dropdown-item" href="/category/Product Pitch">Product Pitch</a>
              <a class="dropdown-item" href="/category/Promotion Pitch">Promotion Pitch</a>
              <a class="dropdown-item" href="/category/Collaboration Pitch">Collaboration Pitch</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
      <!--<ul class="nav navbar-nav navbar-right">-->
        <!--{% if current_user.is_authenticated %}-->
        <!--<li style="color:white;padding:15px;">{{current_user.username}}</li>-->
        <!--<li><a href="{{url_for('auth.logout')}}">Sign out</a></li>-->
        <!--{% else %}-->
        <!--<li><a href="{{url_for('auth.login')}}">Sign in</a></li>-->
        <!--{%endif%}-->
      <!--</ul>-->
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a class="btn btn-outline-primary" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <div></div>
        <li><a class="btn btn-outline-success" href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a class="btn btn-outline-warning" href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="jumbotron">
        <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                <h1 class="card-title">{{pitch.title}}</h1>
                <p>{{pitch.pitch}}</p>
        </div>

        <div class="col-md-8 offst-md-4">
            <h1>{{title}}</h1>

            {{ wtf.quick_form(form) }}
        </div>

    </div>

{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="jumbotron">

        <div class="col-md-8">

            {{ wtf.quick_form(pitch_form) }}
            <!-- {{simplemde.load}} -->
        </div>

    </div>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}

{% block content %}

<div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header">{{the_pitch.title}}</div>
    <div class="card-body">
        <h5 class="card-title">{{the_pitch.pitch}}</h5>
        <a class="btn btn-primary" href="/pitch/new_comment/{{the_pitch.id}}">ADD COMMENT</a>
    </div>

</div>
<h2> <em>COMMENTS</em> </h2>
<div class="jumbotron">

    {% for comment in comments %}


    <div class="container-fluid">
        <div class="card">
            <p>{{comment.comment}}</p>
        </div>
    </div>


</div>
    {% endfor %}
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">
            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

            {%else%}
            <p>No profile picture</p>

            {% endif %}

            {% if user == current_user %}
            <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

                <input type="file"  name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
        {% if user == current_user %}
        <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
        {% endif %}
    </div>

</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}